export const GET_CAR_MAKES = "GET_CAR_MAKES";
export const GET_CAR_MAKES_FULFILLED = "GET_CAR_MAKES_FULFILLED";
export const GET_CAR_MAKES_REJECTED = "GET_CAR_MAKES_REJECTED";

export const GET_USERS = "GET_USERS";
export const GET_USERS_FULFILLED = "GET_USERS_FULFILLED";
export const GET_USERS_REJECTED = "GET_USERS_REJECTED";
